name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Merged Branch
        if: github.event.pull_request.merged == true
        run: |
          branch=${{ github.event.pull_request.head.ref }}
          repo=${{ github.repository }}
          token=${{ secrets.GITHUB_TOKEN }}

          curl -X DELETE -H "Authorization: token $token" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/$repo/git/refs/heads/$branch"
